#!/usr/bin/env sh


# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# config status bar
SPACEBAR_HEIGHT=0
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0


# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xfffbf1c7
yabai -m config normal_window_border_color   0xff24292e

yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# mouse settings
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          off # set mouse follows focus mode (default: off)
yabai -m config focus_follows_mouse          off # (default: off, options: off, autoraise, autofocus)

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

# Space labels
yabai -m space 1 --label "main"
yabai -m space 2 --label "brower"
yabai -m space 3 --label "tool"
yabai -m space 4 --label "chat"
yabai -m space 5 --label "note"
yabai -m space 5 --label "other"
# assign app to space
yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^qemu$" space=1
yabai -m rule --add app="^Firefox$" space=4
yabai -m rule --add app="^Debug$" space=4
yabai -m rule --add app="^Postman$" space=5
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Mail$" space=2
yabai -m rule --add app="^Notion$" space=5
yabai -m rule --add app="^Telegram$" space=6
yabai -m rule --add app="^qBittorrent$" space=6
yabai -m rule --add app="^Steam$" space=6
yabai -m rule --add app="^Friend List$" space=6
yabai -m rule --add app="^Edge$" space=6
yabai -m rule --add app="^VLC$" space=6

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off layer=above
yabai -m rule --add app="^System Setting$" manage=off layer=above
yabai -m rule --add app="^Karabiner$" manage=off layer=above

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


echo "yabai configuration loaded.."


