# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
[character]                            
success_symbol = "[🙂](bold yellow)"

[package]
disabled = true

